### ISSUE TITLE
Questions about Classification of Custom Image Dataset

### ISSUE THREAD

**Issue by jbawsume** [XzwHan/CARD#10]
Hi . I read your paper and was really impressed by your results I was also looking into this topic. I had a question about how to modify the config /dataset.yml file I am interested in testing it on the State Farm distracted driver dataset which also has ten classes and was wondering if there are any requirements  for file location and the .yml file I assume I need to create a State Farm.yml file

**Comment by XzwHan** [comment]
Hi @jbawsume, thank you for checking out our work. It is advised to create a new .yml file specifically for a new dataset, as well as a new .sh file under [`classification/training_scripts`](https://github.com/XzwHan/CARD/tree/main/classification/training_scripts) directory to run scripts for both training and evaluation. In the .yml file, you could modify `data.dataroot` argument to specify the directory where you plan to download and store the dataset; there are no requirements for file location as long as it's accessible. You shall also make sure that `data.num_classes` argument is set to $10$.

**Comment by jbawsume** [comment]
Sure thank you for taking the time to respond and one more question is there any requirement for dataset file structure. Currently the dataset is in the format dataset > train , test | train > with the ten sub folders representing the classes and test with only the test images no sub folders inside

**Comment by XzwHan** [comment]
You may check out how we load the image dataset with the `get_dataset` function in [classification/utils.py](https://github.com/XzwHan/CARD/blob/f438209cc3212aed65594e4c4818cac05183eef4/classification/utils.py#L116), specifically Line 116-148.

**Comment by jbawsume** [comment]
Thank you for taking the time to explain that got it
