### ISSUE TITLE
How to visualize accuracy/loss graphs on custom classification dataset?

### ISSUE THREAD

**Issue by saifhassan** [XzwHan/CARD#12]
Hey,

Nice work for both classification and regression. I have implemented code and run both classification and regression and reproduced same results discussed in paper with graphs/visualizations.

I have one query, I have classification dataset for Facial Expression Recognition and applied the code which is available in Imagenet directory and it provided me results like accuracy, but I don't know how to visualize accuracy/loss graphs on this dataset.

**Comment by saifhassan** [comment]
@

> Hey,
> 
> Nice work for both classification and regression. I have implemented code and run both classification and regression and reproduced same results discussed in paper with graphs/visualizations.
> 
> I have one query, I have classification dataset for Facial Expression Recognition and applied the code which is available in Imagenet directory and it provided me results like accuracy, but I don't know how to visualize accuracy/loss graphs on this dataset.

@XzwHan Can you guide me on this?

**Comment by saifhassan** [comment]
And one more thing, Accuracy is not good while training through imagenet directory.

**Comment by XzwHan** [comment]
Hi @saifhassan, please check [Line 321](https://github.com/XzwHan/CARD/blob/main/classification/imagenet/main.py#L321) where the `train` function is called, in which you can extract the recorded loss from the `losses` variable [here](https://github.com/XzwHan/CARD/blob/ebe2f2ae95dc7a7a95e6a71c0c8e1cabf8451087/classification/imagenet/main.py#L351). You may build upon this code with the visualization tool of your choice.
