### ISSUE TITLE
where can i install the trained_aux_cls_ckpt named snapshot_supervised.ckpt?

### ISSUE THREAD

**Issue by Aurora-hao** [XzwHan/CARD#2]
Hi authors, thanks very much for your great work. When I  run your code, I found it miss the trained_aux_cls_ckpt mentioned in the cifar10.yml or cifar100.yml. I wonder where I can install it and run the code successfully.
Looking forward to your reply. Thanks again.

**Comment by XzwHan** [comment]
Hi @Aurora-hao, thank you for your question, good catch! We have uploaded the corresponding folders containing the checkpoints of the pre-trained $\boldsymbol{f_{\phi}}$ networks, to the [`pretrained`](https://drive.google.com/drive/u/2/folders/1FHIKPdx9GHXMJknc4LNMUTqYdgmYzTko) directory on Google Drive. Please let us know if you have trouble accessing these files.

**Comment by Aurora-hao** [comment]
Thanks very much for your reply! I have downloaded it. It helps a lot.
