### ISSUE TITLE
about y_0 and y_t_mean

### ISSUE THREAD

**Issue by gkyustc** [XzwHan/CARD#3]
https://github.com/XzwHan/CARD/blob/a0b0db7c1852e9a8d497735fdaa40a6a4c7c30d4/classification/card_classification.py#L308-L314

Thanks for your impressive work,

May I ask if the y_t_batch and y_0_batch have the same value in every training step? If so, does it mean that E(y_t) = y_0 which is described in formula (28) in the paper?

**Comment by gkyustc** [comment]
sorry, I mean y_T_mean and y_0_batch

**Comment by gkyustc** [comment]
Oh, I am really sorry, I misread the code...

**Comment by XzwHan** [comment]
@gky1993 No problem -- y_t_batch is the sample from the forward diffusion process, with the distribution specified at (8); the mean of this distribution is derived at (28). y_T_mean corresponds to the mean at timestep T; the code enables one to choose it to be f_phi(x) or 0.
