### ISSUE TITLE
Error occurs while running "training_scripts/cifar10.sh" file

### ISSUE THREAD

**Issue by saifhassan** [XzwHan/CARD#8]
Thank you for your wonderful code, I tried imagenet code and it was working, however image classification on cifar10 or mnist gives following error, saying that i donot have permission to download:

I tried to google, performed some changes but didn't work. Can you help me in this.

I am using Ubuntu 20.04.1 LTS, Nvidia RTX 2080

```
ERROR - main.py - 2023-03-27 03:11:39,769 - Traceback (most recent call last):
  File "main.py", line 304, in main
    runner.train()
  File "/home/user1/Documents/research@saif/CARD/classification/card_classification.py", line 167, in train
    data_object, train_dataset, test_dataset = get_dataset(args, config)
  File "/home/user1/Documents/research@saif/CARD/classification/utils.py", line 134, in get_dataset
    train_dataset = torchvision.datasets.CIFAR10(root=config.data.dataroot, train=True,
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 58, in __init__
    self.download()
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 136, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 249, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 61, in download_url
    os.makedirs(root, exist_ok=True)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

INFO - main.py - 2023-03-27 03:11:40,588 - Using device: cuda
INFO - main.py - 2023-03-27 03:11:40,589 - Writing log file to ./results/card_onehot_conditional_results/1000steps/nn/run_1/f_phi_prior_cat_f_phi/f_phi_supervised/logs/cifar10/split_0
INFO - main.py - 2023-03-27 03:11:40,589 - Exp instance id = 351376
INFO - main.py - 2023-03-27 03:11:40,589 - Exp comment = 
ERROR - main.py - 2023-03-27 03:11:42,945 - Traceback (most recent call last):
  File "main.py", line 299, in main
    y_majority_vote_accuracy_all_steps_list = runner.test_image_task()
  File "/home/user1/Documents/research@saif/CARD/classification/card_classification.py", line 832, in test_image_task
    dataset_object, train_dataset, test_dataset = get_dataset(args, config)
  File "/home/user1/Documents/research@saif/CARD/classification/utils.py", line 134, in get_dataset
    train_dataset = torchvision.datasets.CIFAR10(root=config.data.dataroot, train=True,
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 58, in __init__
    self.download()
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 136, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 249, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 61, in download_url
    os.makedirs(root, exist_ok=True)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
```

**Comment by saifhassan** [comment]
> Thank you for your wonderful code, I tried imagenet code and it was working, however image classification on cifar10 or mnist gives following error, saying that i donot have permission to download:
> 
> I tried to google, performed some changes but didn't work. Can you help me in this.
> 
> I am using Ubuntu 20.04.1 LTS, Nvidia RTX 2080
> 
> ```
> ERROR - main.py - 2023-03-27 03:11:39,769 - Traceback (most recent call last):
>   File "main.py", line 304, in main
>     runner.train()
>   File "/home/user1/Documents/research@saif/CARD/classification/card_classification.py", line 167, in train
>     data_object, train_dataset, test_dataset = get_dataset(args, config)
>   File "/home/user1/Documents/research@saif/CARD/classification/utils.py", line 134, in get_dataset
>     train_dataset = torchvision.datasets.CIFAR10(root=config.data.dataroot, train=True,
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 58, in __init__
>     self.download()
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 136, in download
>     download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 249, in download_and_extract_archive
>     download_url(url, download_root, filename, md5)
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 61, in download_url
>     os.makedirs(root, exist_ok=True)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 223, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/data'
> 
> INFO - main.py - 2023-03-27 03:11:40,588 - Using device: cuda
> INFO - main.py - 2023-03-27 03:11:40,589 - Writing log file to ./results/card_onehot_conditional_results/1000steps/nn/run_1/f_phi_prior_cat_f_phi/f_phi_supervised/logs/cifar10/split_0
> INFO - main.py - 2023-03-27 03:11:40,589 - Exp instance id = 351376
> INFO - main.py - 2023-03-27 03:11:40,589 - Exp comment = 
> ERROR - main.py - 2023-03-27 03:11:42,945 - Traceback (most recent call last):
>   File "main.py", line 299, in main
>     y_majority_vote_accuracy_all_steps_list = runner.test_image_task()
>   File "/home/user1/Documents/research@saif/CARD/classification/card_classification.py", line 832, in test_image_task
>     dataset_object, train_dataset, test_dataset = get_dataset(args, config)
>   File "/home/user1/Documents/research@saif/CARD/classification/utils.py", line 134, in get_dataset
>     train_dataset = torchvision.datasets.CIFAR10(root=config.data.dataroot, train=True,
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 58, in __init__
>     self.download()
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 136, in download
>     download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 249, in download_and_extract_archive
>     download_url(url, download_root, filename, md5)
>   File "/home/user1/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 61, in download_url
>     os.makedirs(root, exist_ok=True)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/user1/anaconda3/envs/card2/lib/python3.8/os.py", line 223, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/data'
> ```

I found error.

In `config` folder, I changed `/data/...` to `data/...`. Just by removing slash in beginning.

Sorry for inconvenience.

**Comment by XzwHan** [comment]
Hi @saifhassan, thanks very much for letting us know that the ImageNet code is working. Regarding the issue, you may modify the `dataroot` argument in all .yml files under the `configs` directory -- the one we put there is where we store the corresponding dataset on our machine; feel free to change it to the directory where you plan to download and store the data (see Line 116-148 of [`classification/utils.py`](https://github.com/XzwHan/CARD/blob/f438209cc3212aed65594e4c4818cac05183eef4/classification/utils.py#L116) file).
